language: java
jdk:
  - oraclejdk8
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_QUBE_TOKEN
notifications:
  email: false
